### PR TITLE
Update examples to fix a problem related to a breaking change in Flutter plugins

### PR DESCRIPTION
**Pull request by ChristianEdwardPadilla**
Update examples to fix a problem related to a breaking Flutter plugins (see: https://github.com/flutter/flutter/issues/27226) and a breaking change to ImageStream listener API.

### CODE REVIEW

**Comment by pskink** [comment]
Christian,

thanks a lot, so i should simply press "merge pull request" button and
everything is done?

also, how it works:

oldImageStream?.removeListener(ImageStreamListener(imageLoaded));

if you are creating a new ImageStreamListener so how it can be removed
from oldImageStream?

btw now i would simply use decodeImageFromList function instead of that
ImageProvider stuff (a year ago i was not aware of it)

pskink

**Comment by ChristianEdwardPadilla** [comment]
You should be able to merge it with that button, yes.

Taking a look at ImageStreamListener, the docs have this to say about instances and equality:

```
/// This class overrides [operator ==] and [hashCode] to compare the individual
/// callbacks in the listener, meaning that if you add an instance of this class
/// as a listener (e.g. via [ImageStream.addListener]), you can instantiate a
/// _different_ instance of this class when you remove the listener, and the
/// listener will be properly removed as long as all associated callbacks are
/// equal.
```
(source: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/image_stream.dart)
(docs: https://api.flutter.dev/flutter/painting/ImageStreamListener-class.html)

**Comment by ChristianEdwardPadilla** [comment]
This is an awesome widget by the way! Great work :)

**Comment by pskink** [comment]
that makes sense, thanks for explanation, I must be blind ...

**Comment by pskink** [comment]
thanks, I already merged your two pull requests

**Pull request merged**
